# Include settings for your email server/mailbox below (you probably only need to edit the "production" settings).
# Settings here are used to generate your crontab configuration when running the "whenever" command.
---
development:
test:
production:
  smtp:
    address: "smtp.mailgun.org"
    domain: <%= ENV['MAILGUN_DOMAIN'] %>
    port: 587
    user_name: <%= ENV['MAILGUN_USERNAME'] %>
    password: <%= ENV['MAILGUN_PASSWORD'] %>